### ISSUE TITLE
 Can MPS be used to infer scores on a single picture? Can you provide relevant codes?

### ISSUE THREAD

**Issue by seasnakes** [wangbohan97/Kolors-MPS#4]
示例代码是对两张图片求更好的一张，能用MPS对单张图片推理得分吗？能否提供相关代码。

**Comment by wangbohan97** [comment]
Certainly, you can use `infer_one_sample` function, which can be found in `eval_overall_mps_on_hpdv2.py` or `eval_overall_mps_on_imagereward.py`.

**Comment by seasnakes** [comment]
> Certainly, you can use `infer_one_sample` function, which can be found in `eval_overall_mps_on_hpdv2.py` or `eval_overall_mps_on_imagereward.py`.

I see,thanks!
